dependencies:
  - name: grafana
    version: "5.0.25"
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled
  - name: influxdb
    version: "4.8.1"
    repository: https://helm.influxdata.com/
