influxdb:
  env:
    - name: INFLUXDB_DB
      value: "k6"

grafana:
  enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: influxdb
          type: influxdb
          url: http://storage-influxdb.default.svc.cluster.local:8086/
          database: k6
          access: proxy
          isDefault: true
      editable: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 15
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      k6-load-testing-results:
        gnetId: 2587
        revision: 2
        datasource: influxdb
