image:
  repository: quay.io/presslabs/wordpress-load-tests
  tag: latest
  pullPolicy: Always

influxdb_url: http://metrics-influxdb.default.svc.cluster.local:8086/k6

env:
  site_url: "https://your.site.example.com/"
  woo_api_key: ""
  woo_api_secret: ""
  k6_stages: "5m:50,5m:100,5m:250,5m:300,5m:500,1m:300,1m:100,1m:50"
  k6_vus: 5
  k6_duration: 60s
  k6_iterations: 5
  test_file_path: "tests/woocommerce-order.js"
